### ISSUE TITLE
internal/build checks are running two times

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-angular#19]
The same build checks are running two times: 
![image](https://user-images.githubusercontent.com/90026355/161931255-9d1ad25c-2172-4df2-bd7a-bba0d712a27f.png)

Jozef will provide more details.
Some details:
1. obmedz push na nejaku branch, pull_request-y nechaj 
```
name: ☃ build-and-test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master
  workflow_dispatch:
```

2. if: ${{ github.event.pull_request.draft == false }} napr
```
- name: prepare upload
        run: |
          export UPLOADDIR=/tmp/__upload_pr/
          echo "Using [$UPLOADDIR] as upload dir"
          mkdir -p $UPLOADDIR
          cp -afv ./bin/*.so* $UPLOADDIR
          cp -afv ./bin/image_to_text $UPLOADDIR
          cp -afv ./bin/fforms $UPLOADDIR
          strip $UPLOADDIR/image_to_text $UPLOADDIR/fforms $UPLOADDIR/py*
          ls -lah $UPLOADDIR
        if: ${{ github.event.pull_request.draft == false }}
```
